/* filepath: /Users/rishisuryavanshi/Desktop/chalkpad-website/src/app/layout.tsx */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BaseNavbar } from "@/components/navbar"; // Import your navbar component

// Initialize the Geist fonts
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

// Define CSS variables for custom Satoshi fonts
const satoshiVariables = `
  :root {
    --font-satoshi: 'Satoshi', sans-serif;
  }
`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Define your navigation items
  const menuItems = [
    { label: "Home", link: "/home" },
    { label: "About", link: "/about" },
    { label: "Features", link: "/features" },
    { label: "Contact", link: "/contact" },
  ];

  // Define your profile items (using the TypeScript structure we created)
  const profileItems = {
    type: "custom" as const, // or "avatar" if you want to use the avatar dropdown
    component: (
      <button className="px-4 py-2 bg-primary text-white rounded">
        Sign In
      </button>
    ),
  };

  return (
    <html lang="en">
      <head>
        <style dangerouslySetInnerHTML={{ __html: satoshiVariables }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BaseNavbar
          logoLink="/"
          menuItems={menuItems}
          profileItems={profileItems}
        />
        <main>{children}</main>
      </body>
    </html>
  );
}
